### ISSUE TITLE
Separate coupon booking

### ISSUE THREAD

**Issue by shivank01** [p-society/Online_Rosei#1]
Different booking options for mess 1 and 2. Also, add functionality that If person has booked some particular coupon in one mess, ~~he~~ they can not book it in another mess.
@p-society/2020-batch @p-society/2021-batch  anyone wants to work on this?

**Comment by knrt10** [comment]
Instead of a separate booking, all people can implement is if one side mess is clicked then the same day for other mess should be disabled.

**Comment by knrt10** [comment]
Fixed

**Comment by shivank01** [comment]
Messi!!!
