### ISSUE TITLE
Automatic closing of coupon booking 

### ISSUE THREAD

**Issue by shivank01** [p-society/Online_Rosei#2]
Add a feature so that one cannot book coupon after Thursday 11:59PM.
@p-society/2020-batch @p-society/2021-batch  Anyone wants to work on this?
@knrt10 Add some comments regarding this issue.

**Comment by knrt10** [comment]
Anyone interested had to implement cron job. There are many packages available and might be easy.

**Comment by debck** [comment]
I would like to try ✋

**Comment by knrt10** [comment]
@debck cool. Use this [node-cron](https://www.npmjs.com/package/node-cron. )

**Comment by knrt10** [comment]
@debck let me explain to you what the issue is:-
Right now **god**(one who can delete database so that people can book again coupon for next week). So your work is in admin part. You have to create a cron job so that database is automatically deleted on Monday (12 am). For that package on above comment can be used. I hope this is helpful.

**Comment by shivank01** [comment]
Also, the coupon booking automatically closes at  Thursday 11:59PM and resume from monday.

**Comment by debck** [comment]
@knrt bt how to do the part which @shivank01 bhaiya told.. can't find the proper route to perform that

**Comment by knrt10** [comment]
> Also, the coupon booking automatically closes at Thursday 11:59PM and resume from monday.

@shivank01 that is not possible you will have to manually do it.

**Comment by shivank01** [comment]
@knrt10 In the previous rosei website they were doing this. What they were doing is when we click on book coupon after thursday it redirect it to the error page. This is the code:
`If(fday.equals("Fri") || fday.equals("Sat") ||fday.equals("Sun"))
{
     response.sendRedirect("http://172.16.2.200:8080/rosei/timeout.jsp");
}`

**Comment by knrt10** [comment]
@shivank01 let me explain you why it won’t work. Cron job works when server is up and running. As we are using free service the glitch might me asleep at that time so the API call won’t be executed. Old code was working as it was on localhost and server was up and runnig everytime. I hope you understand

**Comment by shivank01** [comment]
@knrt10 Ohh!!! Ronaldo

**Comment by knrt10** [comment]
Done
